---
- name: Include OS-specific variable
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure NTP packages are installed
  package: name={{ item }} state=present
  with_items:
    - ntp
    - ntpdate

- name: Set timezone
  timezone: 
    name: "{{ timezone_ntp }}"

- name: Create NTP configuration file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
  - restart ntp

